### ISSUE TITLE
Add xray or esp

### ISSUE THREAD

**Issue by corrupt3d** [brudin/Scooby#15]
You should have xray or an esp that allows you to put in a block id such as diamonds (56) and then highlights the blocks for you. Also highlights mobs, players, and chests. also You should allow us to make custom keybinds.

**Comment by brudin** [comment]
Xray - No, there's already an existing forge mod for that, look it up.
ESP - No, no plans on any visual mods on this.  This isn't meant to be used as a full-fledged client, it's just basic pvp stuff.
Custom Keybinds - That would require having a config file, which people would complain about having since it would get them caught or whatever if an admin makes them prove they don't have it via screenshare.
